# Generated by Django 5.0.1 on 2024-01-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='emp_pic',
        ),
        migrations.AddField(
            model_name='home',
            name='home_pic',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='adminPanel/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='home_title',
            field=models.CharField(max_length=50),
        ),
    ]
