# Generated by Django 5.0.1 on 2024-01-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0002_remove_home_emp_pic_home_home_pic_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='home_insert',
        ),
    ]
