# Generated by Django 5.0.1 on 2024-01-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_rename_home_home_insert'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_home_insert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_title', models.CharField(max_length=20)),
                ('sub_short_title', models.CharField(max_length=20)),
                ('home_pic', models.FileField(default=None, max_length=250, null=True, upload_to='adminPanel/')),
            ],
        ),
    ]
