# Generated by Django 5.0.1 on 2024-02-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0005_remove_sub_home_insert_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=50)),
                ('about_slider_pic', models.FileField(default=None, max_length=250, null=True, upload_to='adminPanel/')),
            ],
        ),
    ]
