# Generated by Django 5.0.1 on 2024-02-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0006_about_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_slider_another',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=50)),
                ('about_slider_another_pic', models.FileField(default=None, max_length=250, null=True, upload_to='adminPanel/')),
            ],
        ),
    ]
