# Generated by Django 5.0.1 on 2024-02-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0007_about_slider_another'),
    ]

    operations = [
        migrations.CreateModel(
            name='causes_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=50)),
                ('picture', models.FileField(default=None, max_length=250, null=True, upload_to='adminPanel/')),
            ],
        ),
    ]
